# Generated by Django 5.2 on 2025-05-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCommandes', '0003_metric_description_alter_metric_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Annulée', 'Annulée'), ('Livrée', 'Livrée')], default='pending', max_length=10),
        ),
    ]
