# Generated by Django 5.2.1 on 2025-05-31 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCommandes', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='metric',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Livrée', 'Livrée')], default='En attente', max_length=10),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('condition', models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equal'), ('<=', 'Less or equal'), ('==', 'Equal'), ('!=', 'Not equal')], max_length=2)),
                ('notify_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='GestionCommandes.metric')),
            ],
            options={
                'unique_together': {('metric', 'threshold', 'condition')},
            },
        ),
    ]
