# Generated by Django 5.2.1 on 2025-05-31 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCommandes', '0006_remove_metric_timestamp_remove_metric_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metric',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='MetricValue',
        ),
    ]
