# Generated by Django 5.2.1 on 2025-05-31 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCommandes', '0007_metric_timestamp_metric_value_delete_metricvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='value',
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='GestionCommandes.metric')),
            ],
        ),
    ]
